# Generated by Django 6.0.5 on 2026-05-19 15:33

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User.objects.create_superuser('admin', 'admin@gmail.com', 'BCSC@1556')
    
class Migration(migrations.Migration):

    dependencies = [
        ('host_with_DB', '0001_initial'),
    ]

    operations = [
    ]
